
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Separator } from "@/components/ui/separator";

export default function DocsPage() {
  return (
    <div className="prose prose-invert max-w-4xl mx-auto">
      <h1 className="text-4xl font-bold tracking-tight">Integrated Security Architecture</h1>
      <p className="text-xl text-muted-foreground">A Blueprint for Threat Detection, Incident Response, and Operational Maturity</p>
      
      <Separator className="my-8" />

      <section>
        <h2 className="text-3xl font-semibold">I. Executive Summary: The Necessity of Automation in Security Operations</h2>
        <p>The contemporary threat landscape is characterized by increasing velocity, volume, and sophistication, placing unprecedented pressure on security operations teams. Organizations must transition from reactive, manual defense mechanisms to integrated, automated systems to maintain cybersecurity posture. Within this context, three components—the Security Operations Center (SOC), Security Information and Event Management (SIEM), and Security Orchestration, Automation, and Response (SOAR)—form the essential pillars of modern defensive architecture.</p>
        <p>The core thesis for building an effective detection and response solution centers on the complementary relationship between SIEM and SOAR. SIEM systems serve as the critical nerve center, aggregating and analyzing security event logs from disparate sources to provide real-time visibility and threat detection. While SIEM excels at detecting threats, it traditionally requires significant manual intervention for analysis and response. SOAR technology explicitly addresses this limitation, providing the crucial efficiency and speed needed to manage overwhelming alert volumes by automating response workflows.</p>
        <p>The organizational success of any security architecture is quantified through key performance indicators (KPIs) that measure efficiency and effectiveness. The integration of SIEM and SOAR is paramount in minimizing the attack dwell time. SIEM focuses primarily on reducing the Mean Time to Detect (MTTD)—the average time elapsed between an incident occurring and its identification. Conversely, SOAR’s specialized function is to drastically reduce the Mean Time to Resolve/Respond (MTTR) by automating containment and remediation actions.</p>
        <p>The architectural challenge inherent in modern security operations is achieving the tight coupling necessary to swiftly convert an alert, generated by the SIEM, into a measured, rapid, and automated mitigation action orchestrated by the SOAR platform. This tight coupling moves the security posture beyond merely identifying a threat to actively mitigating it at scale.</p>
      </section>

      <Separator className="my-8" />

      <section>
        <h2 className="text-3xl font-semibold">II. The Strategic Context: Understanding the Security Operations Center (SOC)</h2>
        <p>The Security Operations Center (SOC) is the centralized facility responsible for executing the security strategy, encompassing the monitoring, detection, analysis, and response processes related to security incidents. Designing robust threat detection and response software requires a thorough understanding of the operational environment and the specific human roles the software supports.</p>
        
        <h3 className="text-2xl font-semibold mt-6">Operational Structure: Tiers of Incident Handling</h3>
        <p>The SOC typically operates using a tiered model that escalates incidents based on complexity and severity, ensuring resources are efficiently allocated.</p>
        
        <h4 className="text-xl font-semibold mt-4">Tier 1: Triage Specialist</h4>
        <p>The Tier 1 analyst operates as the frontline defense. Their primary responsibilities include collecting raw data, configuring security monitoring tools, reviewing initial alarms and alerts, and performing vulnerability scans and reporting. A critical function of the Tier 1 analyst is the True/False Positive Assessment, where they review the severity and relevancy of new threats to reduce noise and create support tickets for issues requiring deeper investigation.</p>

        <h4 className="text-xl font-semibold mt-4">Tier 2: Incident Responder</h4>
        <p>Tier 2 analysts handle higher-priority security incidents that have been escalated by Tier 1 specialists. They conduct in-depth assessments, often leveraging threat intelligence (such as indicators of compromise or updated detection rules) to analyze the root cause. Their focus shifts toward immediate incident response and containment measures.</p>

        <h4 className="text-xl font-semibold mt-4">Tier 3: Threat Hunter/Architect</h4>
        <p>Tier 3 analysts represent the most experienced technical workforce within the SOC. They engage in proactive threat hunting, forensic analysis, post-incident review, and the crucial task of developing and refining new detection rules. The activities of Tier 3 analysts ensure ongoing improvement and the continuous evolution of the organization’s security posture.</p>

        <h3 className="text-2xl font-semibold mt-6">The Standardized Alert Triage Process</h3>
        <p>A structured and cohesive workflow is indispensable for effective security operations. The alert triage process follows several defined stages:</p>
        <ol className="list-decimal pl-6 space-y-2">
            <li><strong>Collecting Alerts:</strong> Ingesting raw alerts from the SIEM or other detection systems.</li>
            <li><strong>Categorizing Alerts:</strong> Grouping alerts by type (e.g., malware, unauthorized access, policy violation).</li>
            <li><strong>Prioritizing Alerts:</strong> Assigning priority based on factors such as category, severity, potential impact, threat intelligence context, and the value of the assets involved.</li>
            <li><strong>Analyzing Alerts:</strong> Verifying the legitimacy of the alert, often involving cross-referencing indicators with threat intelligence. If assessed as a false positive, the analyst may choose to tune the alert or suppress it.</li>
            <li><strong>Incident Response:</strong> Upon confirmation of a true positive, the process escalates to the execution of predefined actions encompassing containment, eradication, and recovery measures.</li>
            <li><strong>Ongoing Improvement:</strong> Post-incident review, refinement of detection rules, and feedback mechanisms.</li>
        </ol>
        <p className="mt-4">The introduction of SOAR technology fundamentally changes the Tier 1 function. Since SOAR can automatically perform alert prioritization, indicator validation, and initial containment, it effectively automates the majority of the repetitive, low-level tasks previously assigned to Tier 1 analysts. This dramatically increases the scalability of the human SOC team, allowing personnel to focus their expertise on complex escalations and strategic threat hunting (T2/T3 work).</p>

        <h3 className="text-2xl font-semibold mt-6">Measuring Security Success: Key Incident Response Metrics</h3>
        <p>Measuring the performance of the SOC infrastructure is achieved by tracking specific Incident Response (IR) KPIs.</p>
        <ul className="list-disc pl-6 space-y-2">
            <li><strong>Mean Time to Detect (MTTD):</strong> The average duration from the moment a security incident occurs until the security team detects it.</li>
            <li><strong>Mean Time to Resolve (MTTR):</strong> The average time required to fully resolve a security failure, including detection, diagnosis, repair, and ensuring the issue will not recur.</li>
            <li><strong>Mean Time to Acknowledgment (MTTA):</strong> The time it takes for the incident response team to acknowledge a reported incident.</li>
        </ul>
      </section>

      <Card className="my-8">
        <CardHeader>
          <CardTitle>Table 1: Functional Comparison of SIEM and SOAR</CardTitle>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Feature</TableHead>
                <TableHead>SIEM (Detection Engine)</TableHead>
                <TableHead>SOAR (Response Engine)</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell className="font-medium">Primary Focus</TableCell>
                <TableCell>Threat Detection and Visibility</TableCell>
                <TableCell>Incident Response, Automation, and Efficiency</TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-medium">Core Function</TableCell>
                <TableCell>Collect, Normalize, Correlate Logs and Data</TableCell>
                <TableCell>Orchestrate, Automate, and Execute Predefined Actions</TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-medium">Input Data</TableCell>
                <TableCell>High-volume, raw, unstructured security event logs</TableCell>
                <TableCell>Structured security alerts, incident data, and threat intelligence</TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-medium">Response Type</TableCell>
                <TableCell>Manual intervention required after alerting</TableCell>
                <TableCell>Automated response via playbooks and integrations</TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-medium">Key Metric Impacted</TableCell>
                <TableCell>Mean Time to Detect (MTTD)</TableCell>
                <TableCell>Mean Time to Resolve (MTTR)</TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </CardContent>
      </Card>
      
      <Card className="my-8">
        <CardHeader>
          <CardTitle>Table 2: Mapping SOC Tiers to Alert Triage Process</CardTitle>
        </CardHeader>
        <CardContent>
            <Table>
                <TableHeader>
                    <TableRow>
                        <TableHead>SOC Tier</TableHead>
                        <TableHead>Role/Title</TableHead>
                        <TableHead>Key Responsibilities</TableHead>
                        <TableHead>Alert Triage Phase</TableHead>
                    </TableRow>
                </TableHeader>
                <TableBody>
                    <TableRow>
                        <TableCell>Tier 1</TableCell>
                        <TableCell>Triage Specialist</TableCell>
                        <TableCell>Initial alert review, categorization, and monitoring tool configuration</TableCell>
                        <TableCell>Assessment (Priority, True/False Positive)</TableCell>
                    </TableRow>
                    <TableRow>
                        <TableCell>Tier 2</TableCell>
                        <TableCell>Incident Responder</TableCell>
                        <TableCell>In-depth assessment, root cause analysis, utilizing threat intelligence</TableCell>
                        <TableCell>Incident Response (Containment, Eradication)</TableCell>
                    </TableRow>
                    <TableRow>
                        <TableCell>Tier 3</TableCell>
                        <TableCell>Threat Hunter/Architect</TableCell>
                        <TableCell>Proactive hunting, forensic analysis, detection rule refinement</TableCell>
                        <TableCell>Remediation, Post-incident Analysis, Ongoing Improvement</TableCell>
                    </TableRow>
                </TableBody>
            </Table>
        </CardContent>
      </Card>

      <section>
        <h2 className="text-3xl font-semibold">VII. Conclusions and Recommendations for the Prototype Build</h2>
        <h3 className="text-2xl font-semibold mt-6">Phase 1: Building the Detection Core (Simulated SIEM)</h3>
        <p>The initial focus must be on establishing the data foundation. The prototype should simulate a data pipeline that includes a Collector/Normalizer module to ingest simulated security logs and transform them into a normalized format suitable for analysis. The core deliverable of this phase is a correlation engine that executes rule-based logic using time windows, sequence checking, and logical operators. Crucially, the output alert database must include mandatory fields for severity and the corresponding MITRE Tactic/Technique.</p>

        <h3 className="text-2xl font-semibold mt-6">Phase 2: Building the Automation Layer (Simulated SOAR Playbook Engine)</h3>
        <p>Once the SIEM core generates reliable, high-context alerts, the SOAR Orchestrator module should be built to ingest these alerts instantly. The most impactful demonstration is implementing a simulated Phishing Incident Response Playbook. This playbook should automate the triage and enrichment steps (e.g., simulating API calls to check IOCs against a mock threat intelligence feed). Finally, the playbook should simulate containment actions—by printing the exact command that would be executed (e.g., "Isolate Host X at EDR")—to demonstrate rapid, automated remediation.</p>

        <h3 className="text-2xl font-semibold mt-6">Presentation Strategy and Operational Context</h3>
        <p>For the class presentation (PPT), the narrative should focus on the value chain transformation realized by integrating SIEM and SOAR. Avoid overwhelming the audience with low-level logs. Instead, quantify the efficiency gain using metrics:</p>
        <ul className="list-disc pl-6 space-y-2">
            <li><strong>Before Automation:</strong> Present a scenario where a manual response takes hours, resulting in a high MTTR.</li>
            <li><strong>After Automation:</strong> Demonstrate the SOAR system completing containment in seconds, showing a dramatic reduction in MTTR.</li>
        </ul>
        <p className="mt-4">Furthermore, demonstrate a nuanced understanding of security operations by referencing operational maturity models, such as the SOC-CMM (Capability Maturity Model). The prototype represents a crucial capability improvement, moving the organization's security operation from an Initial (ad-hoc) or Non-existent state to a Managed capability level in detection and response. The ability to continuously measure and improve performance (using MTTD and MTTR) places the architecture on a trajectory toward a Quantitatively Managed and Optimizing security operation.</p>
      </section>

      <Separator className="my-8" />

      <footer>
        <h3 className="text-2xl font-semibold">Works Cited</h3>
        <ol className="list-decimal pl-6 space-y-2 text-sm text-muted-foreground mt-4">
            <li>Observability 101: What are the differences Between SIEM, SoC, and SOAR? - Observo AI</li>
            <li>SIEM vs SOAR: What's The Difference? - Splunk</li>
            <li>SOAR vs. SIEM: Key Differences - Check Point Software Technologies</li>
            <li>What is SOAR (Security Orchestration, Automation, and Response)? - Balbix</li>
            <li>Top 8 Incident Response Metrics To Know - Splunk</li>
            <li>SIEM vs. SOAR: A Comparative Analysis - SentinelOne</li>
            <li>What is Alert Triage? SOC Alert Triage Process Explained - Radiant Security</li>
            <li>Security Operations Center (SOC) Roles and Responsibilities - Palo Alto Networks</li>
            <li>SOC Analyst Tiers 1, 2, 3 for Cybersecurity | ConnectWise</li>
            <li>What Is Alert Triage in Cybersecurity? Steps, Challenges, and Tips | Corelight</li>
            <li>10 SOAR Use Cases with Real-World Workflow Examples - AIMultiple</li>
            <li>MTBF, MTTR, MTTF, MTTA: Understanding incident metrics - Atlassian</li>
            <li>SOAR vs. SIEM: What Is the Difference? - Palo Alto Networks</li>
            <li>SIEM Log Management: Log Management in the Future SOC - Exabeam</li>
            <li>What Is SIEM? 7 Pillars and 13 Core Features [2025 Guide] - Exabeam</li>
        </ol>
      </footer>
    </div>
  )
}
